### ISSUE TITLE
holstein

### ISSUE THREAD

**Issue by ajkim0630** [ajkim0630/practice-problems#12]
the problem right now is that when it reaches the last list, it clears the entire solution list instead of just going back to the list before that

**Comment by jybluekim** [comment]
Here is the issue. You should NOT clear out solution like below. You should just pop one at the end (i.e. solution.pop() instead of making it 0-size). In this example. you are at level 2 and your solution is currently [2, 1, 0]. You want to just pop the end and make it [2, 1]. In the next iteration of while loop, you will pop again and make it [2], then go down the path of [2, 0], followed by [2, 0, 1].

Try it and let me know whether you can enumerate all solutions. 

        else:

            solution.append(current_lst[level].pop())  # add to the solution list that will be tested

            if level == len(feeds)-1: #if you've reached the bottom and need to move up
                all_solutions.append(solution) #adding to the list of all solutions
                solution = [] #resetting the solution list to make a new solution

**Comment by jybluekim** [comment]
I pushed my changes. Please review.

**Comment by jybluekim** [comment]
This can be closed now right?
